Apns2 fixes for handling CONNRESET and priority
blueshift-labs/rpush pull request #5
Opened 2021-04-28 08:37 UTC by rajesh-blueshift

2021-04-28 17:08 UTC, chongbomb requested changes
The base branch we use is actually redis_cluster_4.2.0_fixes. Can you update to reflect that?

2021-04-28 17:08 UTC, chongbomb commented on lib/rpush/daemon/apns2/delivery.rb
> +          headers['apns-expiration'] = '0'
The headers in `notification_data` should take precedence, take a look at the implementation in https://github.com/rpush/rpush/pull/579/files

2021-04-28 17:10 UTC, rajesh-blueshift commented
> The base branch we use is actually redis_cluster_4.2.0_fixes. Can you update to reflect that?

Sure

2021-04-28 17:11 UTC, rajesh-blueshift commented
@chongbomb , I made the CONNRESET retries bounded now. If it exceeds, then the push will be marked failed.

2021-04-28 17:19 UTC, rajesh-blueshift commented on lib/rpush/daemon/apns2/delivery.rb
> +          headers['apns-expiration'] = '0'
Done

2021-04-29 05:53 UTC, chongbomb approved these changes

2021-04-29 06:06 UTC, merged